/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package in2.liferay.crud.horari.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import in2.liferay.crud.horari.model.Horari;
import in2.liferay.crud.horari.model.HorariModel;
import in2.liferay.crud.horari.model.HorariSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Horari service. Represents a row in the &quot;Horari_Horari&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HorariModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HorariImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HorariImpl
 * @generated
 */
@JSON(strict = true)
public class HorariModelImpl
	extends BaseModelImpl<Horari> implements HorariModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a horari model instance should use the <code>Horari</code> interface instead.
	 */
	public static final String TABLE_NAME = "Horari_Horari";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"fooId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"desde", Types.TIMESTAMP}, {"hasta", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fooId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("desde", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hasta", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Horari_Horari (uuid_ VARCHAR(75) null,fooId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,desde DATE null,hasta DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Horari_Horari";

	public static final String ORDER_BY_JPQL = " ORDER BY horari.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Horari_Horari.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long USERNAME_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long USERID_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Horari toModel(HorariSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Horari model = new HorariImpl();

		model.setUuid(soapModel.getUuid());
		model.setFooId(soapModel.getFooId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDesde(soapModel.getDesde());
		model.setHasta(soapModel.getHasta());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Horari> toModels(HorariSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Horari> models = new ArrayList<Horari>(soapModels.length);

		for (HorariSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public HorariModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fooId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFooId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fooId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Horari.class;
	}

	@Override
	public String getModelClassName() {
		return Horari.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Horari, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Horari, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Horari, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Horari)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Horari, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Horari, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Horari)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Horari, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Horari, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Horari>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Horari.class.getClassLoader(), Horari.class, ModelWrapper.class);

		try {
			Constructor<Horari> constructor =
				(Constructor<Horari>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Horari, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Horari, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Horari, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Horari, Object>>();
		Map<String, BiConsumer<Horari, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Horari, ?>>();

		attributeGetterFunctions.put("uuid", Horari::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Horari, String>)Horari::setUuid);
		attributeGetterFunctions.put("fooId", Horari::getFooId);
		attributeSetterBiConsumers.put(
			"fooId", (BiConsumer<Horari, Long>)Horari::setFooId);
		attributeGetterFunctions.put("groupId", Horari::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Horari, Long>)Horari::setGroupId);
		attributeGetterFunctions.put("companyId", Horari::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Horari, Long>)Horari::setCompanyId);
		attributeGetterFunctions.put("userId", Horari::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Horari, Long>)Horari::setUserId);
		attributeGetterFunctions.put("userName", Horari::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Horari, String>)Horari::setUserName);
		attributeGetterFunctions.put("createDate", Horari::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Horari, Date>)Horari::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Horari::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Horari, Date>)Horari::setModifiedDate);
		attributeGetterFunctions.put("desde", Horari::getDesde);
		attributeSetterBiConsumers.put(
			"desde", (BiConsumer<Horari, Date>)Horari::setDesde);
		attributeGetterFunctions.put("hasta", Horari::getHasta);
		attributeSetterBiConsumers.put(
			"hasta", (BiConsumer<Horari, Date>)Horari::setHasta);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getFooId() {
		return _fooId;
	}

	@Override
	public void setFooId(long fooId) {
		_fooId = fooId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask = -1L;

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask |= USERNAME_COLUMN_BITMASK;

		if (_originalUserName == null) {
			_originalUserName = _userName;
		}

		_userName = userName;
	}

	public String getOriginalUserName() {
		return GetterUtil.getString(_originalUserName);
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getDesde() {
		return _desde;
	}

	@Override
	public void setDesde(Date desde) {
		_desde = desde;
	}

	@JSON
	@Override
	public Date getHasta() {
		return _hasta;
	}

	@Override
	public void setHasta(Date hasta) {
		_hasta = hasta;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Horari.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Horari.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Horari toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Horari>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HorariImpl horariImpl = new HorariImpl();

		horariImpl.setUuid(getUuid());
		horariImpl.setFooId(getFooId());
		horariImpl.setGroupId(getGroupId());
		horariImpl.setCompanyId(getCompanyId());
		horariImpl.setUserId(getUserId());
		horariImpl.setUserName(getUserName());
		horariImpl.setCreateDate(getCreateDate());
		horariImpl.setModifiedDate(getModifiedDate());
		horariImpl.setDesde(getDesde());
		horariImpl.setHasta(getHasta());

		horariImpl.resetOriginalValues();

		return horariImpl;
	}

	@Override
	public int compareTo(Horari horari) {
		int value = 0;

		if (getUserId() < horari.getUserId()) {
			value = -1;
		}
		else if (getUserId() > horari.getUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Horari)) {
			return false;
		}

		Horari horari = (Horari)obj;

		long primaryKey = horari.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		HorariModelImpl horariModelImpl = this;

		horariModelImpl._originalUuid = horariModelImpl._uuid;

		horariModelImpl._originalGroupId = horariModelImpl._groupId;

		horariModelImpl._setOriginalGroupId = false;

		horariModelImpl._originalCompanyId = horariModelImpl._companyId;

		horariModelImpl._setOriginalCompanyId = false;

		horariModelImpl._originalUserName = horariModelImpl._userName;

		horariModelImpl._setModifiedDate = false;

		horariModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Horari> toCacheModel() {
		HorariCacheModel horariCacheModel = new HorariCacheModel();

		horariCacheModel.uuid = getUuid();

		String uuid = horariCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			horariCacheModel.uuid = null;
		}

		horariCacheModel.fooId = getFooId();

		horariCacheModel.groupId = getGroupId();

		horariCacheModel.companyId = getCompanyId();

		horariCacheModel.userId = getUserId();

		horariCacheModel.userName = getUserName();

		String userName = horariCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			horariCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			horariCacheModel.createDate = createDate.getTime();
		}
		else {
			horariCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			horariCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			horariCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date desde = getDesde();

		if (desde != null) {
			horariCacheModel.desde = desde.getTime();
		}
		else {
			horariCacheModel.desde = Long.MIN_VALUE;
		}

		Date hasta = getHasta();

		if (hasta != null) {
			horariCacheModel.hasta = hasta.getTime();
		}
		else {
			horariCacheModel.hasta = Long.MIN_VALUE;
		}

		return horariCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Horari, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Horari, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Horari, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Horari)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Horari, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Horari, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Horari, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Horari)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Horari>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _fooId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private String _originalUserName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _desde;
	private Date _hasta;
	private long _columnBitmask;
	private Horari _escapedModel;

}